//! Auto-converted from MBForge native tools to `#[rig_tool]` impls.
//!
//! Generated by ref/migrate_to_rig.py — review manually before committing.

use rig_core::tool::Tool;
use rig_derive::rig_tool;
// Generated by ref/migrate_to_rig.py.
// Helpers come from arxiv.rs.
use crate::core::agent::arxiv as arxiv_src;
use arxiv_src::{args_err, param_url, json, text, BASE_ARXIV, BASE_PMC, urlencoding};

#[rig_tool(
    name = "arxiv_metadata",
    description = "获取 arXiv 论文的完整元数据（标题、摘要、作者、章节列表、token 计数等）",
    params(
        arxiv_id = "arXiv paper ID, e.g. 2409.05591",
        token = "Optional API token (free papers 2409.05591, 2504.21776 don't need it)",
    )
)]
async fn arxiv_metadata(arxiv_id: String, token: String) -> Result<String, rig_core::tool::ToolError> {

    let id = arxiv_id.clone();
    if id.is_empty() {
        return Ok(args_err("arxiv_id is required"));
    }
    let url = param_url(
        BASE_ARXIV,
        &[("type", "head"), ("arxiv_id", &id), ("token", &token)],
    );
    match json(&url) {
        Ok(v) => Ok(v.to_string()),
        Err(e) => Ok(args_err(&e)),
    }

}

#[rig_tool(
    name = "arxiv_brief",
    description = "获取 arXiv 论文的简要信息（标题、TLDR、关键词、引用数）。适合快速筛选。",
    params(
        arxiv_id = "arXiv paper ID, e.g. 2409.05591",
        token = "Optional API token",
    )
)]
async fn arxiv_brief(arxiv_id: String, token: String) -> Result<String, rig_core::tool::ToolError> {

    let id = arxiv_id.clone();
    if id.is_empty() {
        return Ok(args_err("arxiv_id is required"));
    }
    let url = param_url(
        BASE_ARXIV,
        &[("type", "brief"), ("arxiv_id", &id), ("token", &token)],
    );
    match json(&url) {
        Ok(v) => Ok(v.to_string()),
        Err(e) => Ok(args_err(&e)),
    }

}

#[rig_tool(
    name = "arxiv_preview",
    description = "预览论文的开头部分内容（默认 10000 字符，可调整）。适合移动端或快速浏览引言。",
    params(
        arxiv_id = "arXiv paper ID",
        characters = "预览字符数，范围 100-100000，默认 10000",
        token = "Optional API token",
    )
)]
async fn arxiv_preview(arxiv_id: String, characters: String, token: String) -> Result<String, rig_core::tool::ToolError> {

    let id = arxiv_id.clone();
    if id.is_empty() {
        return Ok(args_err("arxiv_id is required"));
    }
    let chars = characters.parse().unwrap_or(10000);
    let url = param_url(
        BASE_ARXIV,
        &[
            ("type", "preview"),
            ("arxiv_id", &id),
            ("characters", &chars.to_string()),
            ("token", &token),
        ],
    );
    match json(&url) {
        Ok(v) => Ok(v.to_string()),
        Err(e) => Ok(args_err(&e)),
    }

}

#[rig_tool(
    name = "arxiv_raw",
    description = "获取 arXiv 论文的完整内容（Markdown 格式）。适合深入阅读全文。",
    params(
        arxiv_id = "arXiv paper ID",
        token = "Optional API token",
    )
)]
async fn arxiv_raw(arxiv_id: String, token: String) -> Result<String, rig_core::tool::ToolError> {

    let id = arxiv_id.clone();
    if id.is_empty() {
        return Ok(args_err("arxiv_id is required"));
    }
    let url = param_url(
        BASE_ARXIV,
        &[("type", "raw"), ("arxiv_id", &id), ("token", &token)],
    );
    match text(&url) {
        Ok(v) => Ok(serde_json::json!({"content": v}).to_string()),
        Err(e) => Ok(args_err(&e)),
    }

}

#[rig_tool(
    name = "arxiv_section",
    description = "获取论文的特定章节内容，如 Introduction、Methods、Conclusion。",
    params(
        arxiv_id = "arXiv paper ID",
        section = "章节名称，如 Introduction、Methods、Conclusion",
        token = "Optional API token",
    )
)]
async fn arxiv_section(arxiv_id: String, section: String, token: String) -> Result<String, rig_core::tool::ToolError> {

    let id = arxiv_id.clone();
    if id.is_empty() || section.is_empty() {
        return Ok(args_err("arxiv_id and section are required"));
    }
    let url = param_url(
        BASE_ARXIV,
        &[
            ("type", "section"),
            ("arxiv_id", &id),
            ("section", &section),
            ("token", &token),
        ],
    );
    match text(&url) {
        Ok(v) => Ok(serde_json::json!({"section": section, "content": v}).to_string()),
        Err(e) => Ok(args_err(&e)),
    }

}

#[rig_tool(
    name = "arxiv_search",
    description = "跨 arXiv/bioRxiv/medRxiv 统一语义检索论文。支持多维度过滤。",
    params(
        query = "搜索查询（最大 500 字符）",
        source = "来源：arxiv（默认）、biorxiv、medrxiv",
        top_k = "返回结果数 1-100，默认 10",
        offset = "分页偏移，默认 0",
        authors = "作者过滤（逗号分隔）",
        orgs = "机构过滤（逗号分隔）",
        categories = "分类过滤，如 cs.AI,cs.CL（逗号分隔）",
        date_search_type = "日期类型：exact、after、before、between",
        date_str = "日期值，格式 YYYY / YYYY-MM / YYYY-MM-DD；between 时逗号分隔起止",
        min_citation = "最低引用数过滤",
        use_fine_rerank = "是否使用精排（默认 true）",
        return_contents = "是否返回检索到的章节内容（默认 false）",
        return_roc = "是否返回 RoC 列表（默认 false）",
        token = "Optional API token",
    )
)]
async fn arxiv_search(query: String, source: String, top_k: String, offset: String, authors: String, orgs: String, categories: String, date_search_type: String, date_str: String, min_citation: String, use_fine_rerank: String, return_contents: String, return_roc: String, token: String) -> Result<String, rig_core::tool::ToolError> {

    if query.is_empty() {
        return Ok(args_err("query is required"));
    } // arxiv / biorxiv / medrxiv
    let top_k = top_k.parse().unwrap_or(10);
    let offset = offset.parse().unwrap_or(0);
    let min_citation = min_citation.parse().unwrap_or(0);
    let use_fine_rerank = use_fine_rerank.parse().unwrap_or(false);
    let return_contents = return_contents.parse().unwrap_or(false);
    let return_roc = return_roc.parse().unwrap_or(false);

    let mut pairs: Vec<(&str, String)> = vec![
        ("type", "retrieve".into()),
        ("query", query),
        ("top_k", top_k.to_string()),
    ];
    if !source.is_empty() {
        pairs.push(("source", source));
    }
    if offset > 0 {
        pairs.push(("offset", offset.to_string()));
    }
    if !categories.is_empty() {
        pairs.push(("categories", categories));
    }
    if !authors.is_empty() {
        pairs.push(("authors", authors));
    }
    if !orgs.is_empty() {
        pairs.push(("orgs", orgs));
    }
    if !date_search_type.is_empty() {
        pairs.push(("date_search_type", date_search_type));
    }
    if !date_str.is_empty() {
        pairs.push(("date_str", date_str));
    }
    if min_citation > 0 {
        pairs.push(("min_citation", min_citation.to_string()));
    }
    if !use_fine_rerank {
        pairs.push(("use_fine_rerank", "false".into()));
    }
    if return_contents {
        pairs.push(("return_contents", "true".into()));
    }
    if return_roc {
        pairs.push(("return_roc", "true".into()));
    }
    if !token.is_empty() {
        pairs.push(("token", token));
    }

    let qs: Vec<String> = pairs
        .iter()
        .map(|(k, v)| format!("{}={}", urlencoding(k), urlencoding(v)))
        .collect();
    let url = format!("{}?{}", BASE_ARXIV, qs.join("&"));

    match json(&url) {
        Ok(v) => Ok(v.to_string()),
        Err(e) => Ok(args_err(&e)),
    }

}

#[rig_tool(
    name = "arxiv_trending",
    description = "获取论文在社交媒体（Twitter/X）上的传播数据，包括推文数、点赞数、浏览数。需要 API token。",
    params(
        arxiv_id = "arXiv paper ID",
        token = "API token（必需）",
    )
)]
async fn arxiv_trending(arxiv_id: String, token: String) -> Result<String, rig_core::tool::ToolError> {

    let id = arxiv_id.clone();
    if id.is_empty() {
        return Ok(args_err("arxiv_id is required"));
    }
    let url = format!(
        "{}/trending_signal?arxiv_id={}&token={}",
        BASE_ARXIV,
        urlencoding(&id),
        urlencoding(&token),
    );
    match json(&url) {
        Ok(v) => Ok(v.to_string()),
        Err(e) => Ok(args_err(&e)),
    }

}

#[rig_tool(
    name = "pmc_metadata",
    description = "获取 PubMed Central (PMC) 论文的元数据（标题、DOI、摘要、作者、类别）。",
    params(
        pmc_id = "PMC paper ID, e.g. PMC544940",
        token = "Optional API token (free papers PMC544940, PMC514704 don't need it)",
    )
)]
async fn pmc_metadata(pmc_id: String, token: String) -> Result<String, rig_core::tool::ToolError> {

    let id = pmc_id.clone();
    if id.is_empty() {
        return Ok(args_err("pmc_id is required"));
    }
    let url = param_url(
        BASE_PMC,
        &[("type", "head"), ("pmc_id", &id), ("token", &token)],
    );
    match json(&url) {
        Ok(v) => Ok(v.to_string()),
        Err(e) => Ok(args_err(&e)),
    }

}

#[rig_tool(
    name = "pmc_json",
    description = "获取 PubMed Central (PMC) 论文的完整 JSON（含全文内容和元数据）。",
    params(
        pmc_id = "PMC paper ID, e.g. PMC514704",
        token = "Optional API token",
    )
)]
async fn pmc_json(pmc_id: String, token: String) -> Result<String, rig_core::tool::ToolError> {

    let id = pmc_id.clone();
    if id.is_empty() {
        return Ok(args_err("pmc_id is required"));
    }
    let url = param_url(
        BASE_PMC,
        &[("type", "json"), ("pmc_id", &id), ("token", &token)],
    );
    match json(&url) {
        Ok(v) => Ok(v.to_string()),
        Err(e) => Ok(args_err(&e)),
    }

}

/// Add all migrated tools to a `ToolSet`. Call from your rig agent builder.
pub fn register_rig_tools(set: &mut rig_core::tool::ToolSet) {
    set.add_tool(ArxivMetadata);
    set.add_tool(ArxivBrief);
    set.add_tool(ArxivPreview);
    set.add_tool(ArxivRaw);
    set.add_tool(ArxivSection);
    set.add_tool(ArxivSearch);
    set.add_tool(ArxivTrending);
    set.add_tool(PmcMetadata);
    set.add_tool(PmcJson);
}
